home:
    path: /
    controller: App\Controller\HomeController::indexAction

login_success:
    path: /login_success
    controller: App\Controller\HomeController::loginAction

doctors:
    path: /doctors
    controller: App\Controller\DoctorController::indexAction

patients:
    path: /patients
    controller: App\Controller\PatientController::indexAction

doctor_schedule:
    path: /doctor_schedule/{doctor_id}
    controller: App\Controller\DoctorController::scheduleAction
    methods:    POST|HEAD

save_consultation:
    path: /save_consultation
    controller: App\Controller\ConsultationController::askForConsultationAction
    methods:    POST|HEAD

confirm_consultation:
    path: /confirm_consultation/{consultation_id}
    controller: App\Controller\ConsultationController::confirmConsultationAction
    methods:    POST|HEAD

consultation_decision:
    path: /consultation_decision/{consultation_id}
    controller: App\Controller\ConsultationController::saveConsultationDecisionAction
    methods:    POST|HEAD

profile:
    path: /profile
    controller: App\Controller\UserController::showProfileAction

doctor_agenda:
    path: /doctor_agenda
    controller: App\Controller\DoctorController::showDoctorAgendaAction

patient_agenda:
    path: /patient_agenda
    controller: App\Controller\PatientController::showPatientAgendaAction

doctor_consultations:
    path: /doctor_consultations
    controller: App\Controller\ConsultationController::getDoctorConsultationsAction
    methods:    POST|HEAD|GET

patient_consultations:
    path: /patient_consultations
    controller: App\Controller\ConsultationController::getPatientConsultationsAction

view_patient_consultation:
    path: /view_patient_consultation/{consultation_id}
    controller: App\Controller\ConsultationController::viewPatientConsultationAction
    options:
        expose: true

edit_patient_consultation:
    path: /edit_patient_consultation/{consultation_id}
    controller: App\Controller\ConsultationController::editPatientConsultationAction