home:
    path: /
    controller: App\Controller\HomeController::indexAction

doctors:
    path: /doctors
    controller: App\Controller\DoctorsController::indexAction

patients:
    path: /patients
    controller: App\Controller\PatientsController::indexAction

doctor_schedule:
    path: /doctor_schedule/{doctor_id}
    controller: App\Controller\DoctorsController::scheduleAction
    methods:    POST|HEAD

save_consultation:
    path: /save_consultation
    controller: App\Controller\ConsultationController::askForConsultationAction
    methods:    POST|HEAD

confirm_consultation:
    path: /confirm_consultation/{consultation_id}
    controller: App\Controller\ConsultationController::confirmConsultationAction
    methods:    POST|HEAD

consultation_decision:
    path: /consultation_decision/{consultation_id}
    controller: App\Controller\ConsultationController::confirm_consultation
    methods:    POST|HEAD

profile:
    path: /profile
    controller: App\Controller\UserController::showProfileAction

doctor_agenda:
    path: /doctor_agenda
    controller: App\Controller\UserController::showDoctorAgendaAction

patient_agenda:
    path: /patient_agenda
    controller: App\Controller\UserController::showPatientAgendaAction